const C = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  RESET: "RESET",

  // Auth statuses
  ANONYMOUS: "ANONYMOUS",
  AWAITING: "AWAITING",
  AUTHENTICATED: "AUTHENTICATED",

  // Auth actions
  ATTEMPT_AUTHENTICATE: "ATTEMPT_AUTHENTICATE",
  AUTHENTICATE: "AUTHENTICATE",
  DEAUTHENTICATE: "DEAUTHENTICATE",

  // API KEY
  API_KEY: "30f6320f68d94d5987f025ed6f646aa3",

  BASE_API_URL: "http://lit-river-92285.herokuapp.com/api"

};

export default C;
